### ISSUE TITLE
Crash on Shield TV

### ISSUE THREAD

**Issue by ikogan** [ITVlab/TvAppRepo#42]
Installed the OpenCommunity APK on a 2017 Shield TV with the latest 5.0.1 update and the application crashes immediately.

```01-19 22:19:06.069   693  2600 I ActivityManager: Start proc 25012:news.androidtv.tvapprepo/u0a83 for activity news.androidtv.tvapprepo/.activities.MainActivity
01-19 22:19:06.089 25012 25012 W System  : ClassLoader referenced unknown path: /data/app/news.androidtv.tvapprepo-1/lib/arm64
01-19 22:19:06.103 25012 25012 D FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
01-19 22:19:06.107 25012 25012 D FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
01-19 22:19:06.111 25012 25012 I FA      : App measurement is starting up, version: 10084
01-19 22:19:06.111 25012 25012 I FA      : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
01-19 22:19:06.115 25012 25012 I FA      : To enable faster debug mode event logging run:
01-19 22:19:06.115 25012 25012 I FA      :   adb shell setprop debug.firebase.analytics.app news.androidtv.tvapprepo
01-19 22:19:06.122 25012 25012 I FirebaseInitProvider: FirebaseApp initialization successful
01-19 22:19:06.176 25012 25012 I CrashlyticsCore: Initializing Crashlytics 2.3.14.151
01-19 22:19:06.185 25012 25012 I MainFragment: onCreate
01-19 22:19:06.198 25012 25012 D MainFragment: Get RepoDatabase instance
01-19 22:19:06.206 25012 25042 D NetworkSecurityConfig: No Network Security Config specified, using platform default
01-19 22:19:06.209 25012 25012 I DynamiteModule: Considering local module com.google.android.gms.firebase_database:4 and remote module com.google.android.gms.firebase_database:4
01-19 22:19:06.209 25012 25012 I DynamiteModule: Selected remote version of com.google.android.gms.firebase_database, version >= 4
01-19 22:19:06.214 25012 25012 W System  : ClassLoader referenced unknown path: /data/user/0/com.google.android.gms/app_chimera/m/00000006/n/arm64-v8a
01-19 22:19:06.223 25012 25012 D d       : Create new instance
01-19 22:19:06.269 25012 25012 D MainFragment: [ResolveInfo{e523280 com.nvidia.shield.welcome/.WebViewer m=0x108000}, ResolveInfo{362b0b9 mobi.mgeek.TunnyBrowser/.BrowserActivity m=0x108000}, ResolveInfo{af3ccfe com.android.documentsui/.LauncherActivity m=0x108000}, ResolveInfo{cb7dc5f com.nvidia.blakepairing/.BlakePairingLoadingActivity m=0x108000}, ResolveInfo{fe7f6ac com.nvidia.inputviewer/.MainActivity m=0x108000}, ResolveInfo{7f49f75 com.plexapp.mediaserver.smb/com.plexapp.mediaserver.MainActivity m=0x108000}]
01-19 22:19:06.296 25012 25012 D MainFragment: Get RepoDatabase instance
01-19 22:19:06.344 25012 25012 D MainFragment: [ResolveInfo{b809672 com.nvidia.shield.welcome/.WebViewer m=0x108000}, ResolveInfo{1c2fac3 mobi.mgeek.TunnyBrowser/.BrowserActivity m=0x108000}, ResolveInfo{e3e5f40 com.android.documentsui/.LauncherActivity m=0x108000}, ResolveInfo{d143e79 com.nvidia.blakepairing/.BlakePairingLoadingActivity m=0x108000}, ResolveInfo{73da7be com.nvidia.inputviewer/.MainActivity m=0x108000}, ResolveInfo{950801f com.plexapp.mediaserver.smb/com.plexapp.mediaserver.MainActivity m=0x108000}]
01-19 22:19:06.368 25012 25012 D phs:ipc-binder-client: phs: RegisterClient(): transact returned 0, NO_ERROR=0
01-19 22:19:06.368 25012 25012 D phs:ipc-binder-client: phs: RegisterClient() timeout is 5000
01-19 22:19:06.371   759   774 D RSMouse : mFeatureEnabled=true  mPackageEnabled=false
01-19 22:19:06.412 25012 25068 I OpenGLRenderer: Initialized EGL, version 1.4
01-19 22:19:06.412 25012 25068 D OpenGLRenderer: Swap behavior 2
01-19 22:19:06.417 25012 25012 D e       : ResolveInfo{b809672 com.nvidia.shield.welcome/.WebViewer m=0x108000}
01-19 22:19:06.417 25012 25012 D e       : com.nvidia.shield.welcome.WebViewer
01-19 22:19:06.417 25012 25012 D e       : Device Help
01-19 22:19:06.420 25012 25012 D e       : ResolveInfo{1c2fac3 mobi.mgeek.TunnyBrowser/.BrowserActivity m=0x108000}
01-19 22:19:06.420 25012 25012 D e       : mobi.mgeek.TunnyBrowser.BrowserActivity
01-19 22:19:06.420 25012 25012 D e       : Dolphin
01-19 22:19:06.422 25012 25012 D e       : ResolveInfo{e3e5f40 com.android.documentsui/.LauncherActivity m=0x108000}
01-19 22:19:06.422 25012 25012 D e       : com.android.documentsui.LauncherActivity
01-19 22:19:06.422 25012 25012 D e       : Documents
01-19 22:19:06.425 25012 25012 D e       : ResolveInfo{d143e79 com.nvidia.blakepairing/.BlakePairingLoadingActivity m=0x108000}
01-19 22:19:06.425 25012 25012 D e       : com.nvidia.blakepairing.BlakePairingLoadingActivity
01-19 22:19:06.425 25012 25012 D e       : SHIELD Controller
01-19 22:19:06.428 25012 25012 D e       : ResolveInfo{73da7be com.nvidia.inputviewer/.MainActivity m=0x108000}
01-19 22:19:06.428 25012 25012 D e       : com.nvidia.inputviewer.MainActivity
01-19 22:19:06.428 25012 25012 D e       : Input Viewer
01-19 22:19:06.431 25012 25012 D e       : ResolveInfo{950801f com.plexapp.mediaserver.smb/com.plexapp.mediaserver.MainActivity m=0x108000}
01-19 22:19:06.431 25012 25012 D e       : com.plexapp.mediaserver.MainActivity
01-19 22:19:06.431 25012 25012 D e       : Plex Media Server
01-19 22:19:06.566   693  1416 I WindowManager: Destroying surface Surface(name=com.google.android.leanbacklauncher/com.google.android.leanbacklauncher.MainActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2016 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.destroyOrSaveSurface:2087 com.android.server.wm.WindowManagerService.tryStartExitingAnimation:3058 com.android.server.wm.WindowManagerService.relayoutWindow:2938 com.android.server.wm.Session.relayout:216 android.view.IWindowSession$Stub.onTransact:286 com.android.server.wm.Session.onTransact:137
01-19 22:19:06.664   693   713 I ActivityManager: Displayed news.androidtv.tvapprepo/.activities.MainActivity: +606ms
01-19 22:19:06.671  1568  1568 D ViewRootImpl[MainActivity]: changeCanvasOpacity: opaque=false
01-19 22:19:06.672  1568  1568 D ViewRootImpl[MainActivity]: changeCanvasOpacity: opaque=false
01-19 22:19:06.754 25012 25012 D AndroidRuntime: Shutting down VM
01-19 22:19:06.779 25012 25012 E AndroidRuntime: FATAL EXCEPTION: main
01-19 22:19:06.779 25012 25012 E AndroidRuntime: Process: news.androidtv.tvapprepo, PID: 25012
01-19 22:19:06.779 25012 25012 E AndroidRuntime: com.google.firebase.database.c: No properties to serialize found on class news.androidtv.tvapprepo.b.a
01-19 22:19:06.779 25012 25012 E AndroidRuntime: 	at com.google.android.gms.b.lk$a.<init>(Unknown Source)
01-19 22:19:06.779 25012 25012 E AndroidRuntime: 	at com.google.android.gms.b.lk.a(Unknown Source)
01-19 22:19:06.779 25012 25012 E AndroidRuntime: 	at com.google.android.gms.b.lk.e(Unknown Source)
01-19 22:19:06.779 25012 25012 E AndroidRuntime: 	at com.google.android.gms.b.lk.b(Unknown Source)
01-19 22:19:06.779 25012 25012 E AndroidRuntime: 	at com.google.android.gms.b.lk.a(Unknown Source)
01-19 22:19:06.779 25012 25012 E AndroidRuntime: 	at com.google.firebase.database.a.a(Unknown Source)
01-19 22:19:06.779 25012 25012 E AndroidRuntime: 	at news.androidtv.tvapprepo.b.d$1.a(Unknown Source)
01-19 22:19:06.779 25012 25012 E AndroidRuntime: 	at com.google.android.gms.b.hy.a(Unknown Source)
01-19 22:19:06.779 25012 25012 E AndroidRuntime: 	at com.google.android.gms.b.iz.b(Unknown Source)
01-19 22:19:06.779 25012 25012 E AndroidRuntime: 	at com.google.android.gms.b.jd$1.run(Unknown Source)
01-19 22:19:06.779 25012 25012 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
01-19 22:19:06.779 25012 25012 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-19 22:19:06.779 25012 25012 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
01-19 22:19:06.779 25012 25012 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6120)
01-19 22:19:06.779 25012 25012 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-19 22:19:06.779 25012 25012 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
01-19 22:19:06.779 25012 25012 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
01-19 22:19:06.780   693  1529 W ActivityManager:   Force finishing activity news.androidtv.tvapprepo/.activities.MainActivity```

**Comment by Xstar97** [comment]
@ikogan
please try the play store version instead...it worked for me on my shield tv.

**Comment by ikogan** [comment]
That does indeed work, but I'm specifically looking to be able to use the Open Community repo that can't be included in the Play Store version.

**Comment by Fleker** [comment]
Stack trace is here. Not too sure why this is happening on some devices, but it's a place to start.

    Fatal Exception: com.google.firebase.database.c: No properties to serialize found on class news.androidtv.tvapprepo.b.a
       at com.google.android.gms.internal.zzbqi$zza.(Unknown Source)
       at com.google.android.gms.internal.zzbqi.zzaw(Unknown Source)
       at com.google.android.gms.internal.zzbqi.zzaz(Unknown Source)
       at com.google.android.gms.internal.zzbqi.zza(Unknown Source)
       at com.google.android.gms.internal.zzbqi.zzaw(Unknown Source)
       at com.google.firebase.database.DataSnapshot.getValue(Unknown Source)
       at news.androidtv.tvapprepo.model.RepoDatabase$1.onDataChange(Unknown Source)
       at com.google.android.gms.internal.zzbmz.zza(Unknown Source)
       at com.google.android.gms.internal.zzbnz.zzYj(Unknown Source)
       at com.google.android.gms.internal.zzboc$1.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:742)
       at android.os.Handler.dispatchMessage(Handler.java:97)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5482)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by ikogan** [comment]
Clearing data doesn't seem to help. I noticed that when it first starts, it asks for permission to access storage and crashes at the same time. Could the inability to access storage due to permissions have anything to do with it?

Note that when I grant those permissions and open the app again, it keeps crashing.

**Comment by Xstar97** [comment]
@Fleker
Until I get my PC fixed...cant really helped at all...(Im using my shield TV & using google chrome dev)...whats the database used for?

**Comment by Fleker** [comment]
Firebase stores the apps that can be sideloaded. It is easier to do that remotely than hardcoding the list.

As the feature is only in the community version, this is never called in the Play Store version.

**Comment by Xstar97** [comment]
@Fleker 
You might want to look into null values trying to be parse in your code...so I will suggest to check your database & java code for any errors.

**Comment by Fleker** [comment]
It has seemed to work on my devices, so there may be some caching happening on my end

**Comment by ikogan** [comment]
I ran this in debug mode from Studio and it worked fine. Then I generated both an opencommunity and a "release" build. The opencommunity build crashes, the "release" build seems to work fine *and* gives me a list of installable apps.

**Comment by Fleker** [comment]
Yes that is consistent with what others have reported.

**Comment by Fleker** [comment]
I cannot reproduce this error, so I don't know how to fix it

**Comment by Fleker** [comment]
http://stackoverflow.com/questions/37743661/firebase-no-properties-to-serialize-found-on-class

Based on that, I'm still unsure. My POJOs have public getters/setters. One possible issue could be proguard deleting things, so I will apply the `@Keep` annotation and see whether that works in the next version (going up tonight)

**Comment by s2law** [comment]
Had worked perfectly on my shield tv, but hasn't since the android update to 7.0

**Comment by Fleker** [comment]
@s2law which version are you using? Can you say what you were doing when the crash happens?

**Comment by s2law** [comment]
Just launching the app using the latest version from the playstore

**Comment by s2law** [comment]
Version code 6 
Version name 1.0.3-playstore

I literally just launched the app and on every occasion it just crashes.

**Comment by Fleker** [comment]
@s2law your app is out of date. It's received several fixes since. I have also fixed a few bugs this evening.

**Comment by o-l-a-v** [comment]
Shield TV with latest update (5.1) + TvAppRepo v1.0.6 = Still crashes
Even tried uninstalling the whole app, then install. Crashes right after it asks for permissions.

**Comment by o-l-a-v** [comment]
I got some intel that might help you iron out this bug: I think it's the youtuve phone app that crashes it, at least on my nVidia Shield TV. Here is what I did:

- I uninstalled all shortcuts made by TVAppRepo and the TVAppRepo app.
- Install latest latest TVAppRepo from play store.
- Then I opened TVAppRepo, did not crash. 
- I started adding new shortcuts. Everything is cool, new shortcuts keep poppin' up. 
- Then I add youtube, the phone version. TVAppRepo crashes. 
- I remove youtube shortcut created by TVAppRepo. TVAppRepo does not crash anymore.

**Comment by Fleker** [comment]
Does the app crash when you generate the shortcut, open the TV app repo, or
when you open the YouTube shortcut?

**Comment by o-l-a-v** [comment]
Just when youtube shortcut is generated it crashes, and will never open again.

MVH: Olav R. Birkeland


________________________________

**Comment by Fleker** [comment]
I'll take a look at why that's happening.
